{% set name = "biom-format" %}
{% set version = "2.1.16" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 47f88d57a94ecaa4d06f3578ca394e78db6d12e46ab0886634743181e67dcfc9

build:
  number: 0
  skip: true  # [py<36]
  entry_points:
    - biom = biom.cli:cli

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy >=1.9.2                          # [build_platform != target_platform]
    - h5py >=3.0.0                           # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - pip
    - cython
    - numpy >=1.9.2
    - h5py >=3.0.0
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - click
    - pandas >=0.20.0
    - scipy >=1.3.1
    - h5py >=3.0.0

test:
  imports:
    - biom
    - biom._filter
    - biom._transform
    - biom._subsample
  commands:
    - biom --help

about:
  home: http://biom-format.org/
  license: BSD-3-Clause
  license_family: BSD
  license_file: COPYING.txt
  summary: Biological Observation Matrix (BIOM) format
  dev_url: https://github.com/biocore/biom-format

extra:
  recipe-maintainers:
    - synapticarbors
    - wasade
    - nsoranzo
