{% set name = "biom-format" %}
{% set version = "2.1.14" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c8bac94ab6aa8226c0d38af7a3341d65e5f3664b9f45ec44fdf8b5275b2f92c1

build:
  number: 1
  skip: true  # [py<36]
  entry_points:
    - biom = biom.cli:cli

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - cython
    - numpy >=1.9.2
    - h5py
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - click
    - pandas >=0.20.0
    - scipy >=1.3.1
    - h5py

test:
  imports:
    - biom
    - biom._filter
    - biom._transform
    - biom._subsample
  commands:
    - biom --help

about:
  home: http://biom-format.org/
  license: BSD-3-Clause
  license_family: BSD
  license_file: COPYING.txt
  summary: Biological Observation Matrix (BIOM) format
  dev_url: https://github.com/biocore/biom-format

extra:
  recipe-maintainers:
    - synapticarbors
    - wasade
    - nsoranzo
