travis:
  secure:
    BINSTAR_TOKEN: jY+KaAZHkne+nDciG/hPAJZk7yHEdZ/LAiNADo4Kp7mHKUTbikZ5KqTy+BTjJ3tLSzaBK9AvIzwKI3tWYahbUAyPWtcyYeJ31F/0SAwjJxHN+3oT5OfNmzrEzxDXYW3V3H7LdtFiXSN9rDLnpr6kAWY0ay3yor12Z0T9wZUBZ66TxqtEr3gA4W8ypOA7cg7BYj+cHK5JBgP9gDOdMz9QRU3BoFk3uMzUTQbZ5gshzCwD7+UKRXtSCZ5WDoQqh6aK8hNwBtdkkKAF/sK+jQW6WEfb+hcW2bTQv2laTOZjq2/6jSG7ehm9PVmkVadhpZ7dBYP592/luepYzJ6Kqk8ujnfN9RRe8oOO77fQKrqN4ddf7J/Mq3JHdq/U1wnvUlNQXzZMQxupzYGGWc/0zy//WwQko6j2eB2CeO1m/hJbUYDbofQoOPQlhHrdt+psmzY04D/2qwNYA5y7IWnZhJb8BNuDBEdL5B6h4roCS8R/WjKXln6Qu2cXEakKyxzWoeX5lcD1zc5TNlxO729sgKX3tG6T+2FIzaEc1A/2jCv+sG3Xoq+B1RNISest+yWBYA3cVlZp4WBb/79lyDsgucVBfhg/8Qgaf8y9VEKIIN5ks16OXquwvEp9vsFTUfi9W4sjiEVk3TySqANsx36Mi9E8EP+NGDWVIio/qp6wJM2juW0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
